import { useEffect, useMemo, useState } from 'react'
import type { Address, Service, Technician } from '../types'
import { availabilityClient } from '../api/availability'
import { bookingDates, bookingTimes, slotIsPast, weekdayForDate } from '../lib/availability'

interface Props { technician: Technician; service: Service; initialDateIndex: number; initialTime: string; onBack: () => void; onContinue: (details: { dateLabel: string; dateKey: string; time: string; intensity: string; address: Address; note: string }) => void }

const addresses: Address[] = [
  { id: 'home', label: '静安嘉里中心 · 2号楼', detail: '上海市静安区南京西路1515号' },
  { id: 'office', label: '恒隆广场 · 办公楼', detail: '上海市静安区南京西路1266号' },
  { id: 'hotel', label: '上海静安瑞吉酒店', detail: '上海市静安区北京西路1008号' },
]

export function BookingScreen({ technician, service, initialDateIndex, initialTime, onBack, onContinue }: Props) {
  const dates = useMemo(bookingDates, []), times = bookingTimes
  const [dateIndex, setDateIndex] = useState(initialDateIndex), [time, setTime] = useState(initialTime), [intensity, setIntensity] = useState('适中')
  const [address, setAddress] = useState(addresses[0]), [addressOpen, setAddressOpen] = useState(false), [note, setNote] = useState('')
  const [availability, setAvailability] = useState({ occupied: [] as string[], workStart: technician.workStart, workEnd: technician.workEnd, workDays: technician.workDays })
  useEffect(() => { availabilityClient.get(technician.id).then(setAvailability).catch(() => setAvailability({ occupied: [], workStart: technician.workStart, workEnd: technician.workEnd, workDays: technician.workDays })) }, [technician.id])
  const unavailableReason = (day: number, item: string) => slotIsPast(dates[day].dateKey, item) ? '已过时' : !availability.workDays.includes(weekdayForDate(dates[day].dateKey)) ? '休息' : item < availability.workStart || item > availability.workEnd ? '非接单' : availability.occupied.includes(`${dates[day].dateKey}|${item}`) ? '已约满' : ''
  const selectDate = (index: number) => { setDateIndex(index); if (unavailableReason(index, time)) setTime(times.find((item) => !unavailableReason(index, item)) ?? '') }
  useEffect(() => { if (unavailableReason(dateIndex, time)) setTime(times.find((item) => !unavailableReason(dateIndex, item)) ?? '') }, [dateIndex, availability])
  return <section className="screen active"><div className="page-head"><button onClick={onBack}>‹</button><h1>确认预约</h1></div><div className="form-body"><div className="stepper"><div className="book-step active"><i/>选择服务</div><div className="book-step active"><i/>预约时间</div><div className="book-step active"><i/>确认下单</div></div><div className="booking-summary"><img src={technician.img} alt={technician.name}/><span><b>{service.name}</b><small>{technician.name} · {service.desc.split(' · ')[0]}</small></span><span className="sum-price">¥{service.price}</span></div><div className="field"><label>选择日期</label><div className="date-row">{dates.map((date, index) => <button key={date.value} className={`choice ${dateIndex === index ? 'selected' : ''}`} onClick={() => selectDate(index)}><small>{date.label}</small><strong>{date.value}</strong></button>)}</div></div><div className="field"><label>选择上门时间 <small className="field-hint">北京时间 · 档期实时更新</small></label><div className="time-grid">{times.map((item) => { const reason = unavailableReason(dateIndex, item); return <button key={item} disabled={Boolean(reason)} className={`choice ${time === item ? 'selected' : ''}`} onClick={() => !reason && setTime(item)}>{item}{reason && <small>{reason}</small>}</button> })}</div></div><div className="field"><label>偏好力度</label><div className="intensity">{['轻柔','适中','偏重'].map((item) => <button key={item} className={`choice ${intensity === item ? 'selected' : ''}`} onClick={() => setIntensity(item)}>{item}</button>)}</div></div><div className="field"><label>服务地址</label><button className="address-card" onClick={() => setAddressOpen(true)}><span>⌖</span><span><b>{address.label}</b><small>{address.detail}</small></span><strong>更换 ›</strong></button></div><div className="field"><label>给技师留言 <small className="field-hint">选填</small></label><textarea className="note-input" value={note} onChange={(event) => setNote(event.target.value)} placeholder="如：肩颈比较疲劳，请提前电话联系" maxLength={80}/><div className="input-count">{note.length}/80</div></div><p className="notice">技师到达前 30 分钟可免费取消。平台全程隐私保护，服务过程支持紧急联系。</p><div className="paybar"><div className="total">合计<br/><strong>¥{service.price}</strong></div><button className="primary" disabled={!time} onClick={() => onContinue({ dateLabel: `${dates[dateIndex].label} ${dates[dateIndex].value}`, dateKey: dates[dateIndex].dateKey, time, intensity, address, note })}>{time ? '确认并支付' : '当日暂无可约时间'}</button></div></div>
    <div className={`sheet-mask ${addressOpen ? 'open' : ''}`} onClick={() => setAddressOpen(false)}><div className="sheet" onClick={(event) => event.stopPropagation()}><div className="grab"/><h2>选择服务地址</h2><div className="address-options">{addresses.map((item) => <button key={item.id} className={`address-option ${address.id === item.id ? 'selected' : ''}`} onClick={() => { setAddress(item); setAddressOpen(false) }}><i>⌖</i><span><b>{item.label}</b><small>{item.detail}</small></span><strong>{address.id === item.id ? '✓' : '›'}</strong></button>)}</div><button className="secondary add-address" onClick={() => setAddressOpen(false)}>＋ 新增地址（演示）</button></div></div>
  </section>
}
