import { useState } from 'react'
import type { Service, Technician } from '../types'
import { futureDates } from '../data'

interface Props { technician: Technician; service: Service; onBack: () => void; onContinue: (details: { dateLabel: string; time: string; intensity: string }) => void }

export function BookingScreen({ technician, service, onBack, onContinue }: Props) {
  const dates = futureDates(), times = ['15:00','16:30','18:00','19:00','20:30','22:00']
  const [dateIndex, setDateIndex] = useState(0), [time, setTime] = useState('19:00'), [intensity, setIntensity] = useState('适中')
  return <section className="screen active"><div className="page-head"><button onClick={onBack}>‹</button><h1>确认预约</h1></div><div className="form-body"><div className="stepper"><div className="book-step active"><i/>选择服务</div><div className="book-step active"><i/>预约时间</div><div className="book-step active"><i/>确认下单</div></div><div className="booking-summary"><img src={technician.img} alt={technician.name}/><span><b>{service.name}</b><small>{technician.name} · {service.desc.split(' · ')[0]}</small></span><span className="sum-price">¥{service.price}</span></div><div className="field"><label>选择日期</label><div className="date-row">{dates.map((date, index) => <button key={date.value} className={`choice ${dateIndex === index ? 'selected' : ''}`} onClick={() => setDateIndex(index)}><small>{date.label}</small><strong>{date.value}</strong></button>)}</div></div><div className="field"><label>选择上门时间</label><div className="time-grid">{times.map((item) => <button key={item} className={`choice ${time === item ? 'selected' : ''}`} onClick={() => setTime(item)}>{item}</button>)}</div></div><div className="field"><label>偏好力度</label><div className="intensity">{['轻柔','适中','偏重'].map((item) => <button key={item} className={`choice ${intensity === item ? 'selected' : ''}`} onClick={() => setIntensity(item)}>{item}</button>)}</div></div><div className="field"><label>服务地址</label><div className="address-card"><span>⌖</span><span><b>静安嘉里中心 · 2号楼</b><small>上海市静安区南京西路1515号</small></span></div></div><div className="field"><label>给技师留言</label><textarea className="note-input" placeholder="如：肩颈比较疲劳，请提前电话联系"/></div><p className="notice">技师到达前 30 分钟可免费取消。平台全程隐私保护，服务过程支持紧急联系。</p><div className="paybar"><div className="total">合计<br/><strong>¥{service.price}</strong></div><button className="primary" onClick={() => onContinue({ dateLabel: `${dates[dateIndex].label} ${dates[dateIndex].value}`, time, intensity })}>确认并支付</button></div></div></section>
}
