import type { Service, Technician } from '../types'

export interface AppointmentSlot { dateIndex: number; dateLabel: string; time: string }
interface Props { technician: Technician; services: Service[]; selected: Service; selectedSlot: AppointmentSlot; onSelect: (service: Service) => void; onSlotSelect: (slot: AppointmentSlot) => void; onBack: () => void; onBook: () => void }

export function TechnicianDetail({ technician: tech, services, selected, selectedSlot, onSelect, onSlotSelect, onBack, onBook }: Props) {
  const slots: AppointmentSlot[] = [{ dateIndex: 0, dateLabel: '今天', time: '19:00' }, { dateIndex: 0, dateLabel: '今天', time: '20:30' }, { dateIndex: 1, dateLabel: '明天', time: '15:00' }]
  return <section className="screen active"><div className="detail-hero"><img src={tech.img} alt={tech.name}/><button className="back" onClick={onBack}>‹</button><span className="demo-badge">● 现在可接单</span><div className="hero-info"><h1>{tech.name} · {tech.title}</h1><div className="hero-meta"><span>★ {tech.rating}</span><span className="verified">✓ 平台认证</span></div></div></div><div className="detail-body"><p className="intro">{tech.intro}</p><div className="metric-row"><div className="metric"><strong>{tech.orders}</strong><small>累计服务</small></div><div className="metric"><strong>98%</strong><small>准时到达</small></div><div className="metric"><strong>6年+</strong><small>从业经验</small></div></div><h2 className="sub-title">近期可约</h2><div className="calendar-strip">{slots.map((slot, index) => { const active = slot.dateIndex === selectedSlot.dateIndex && slot.time === selectedSlot.time; return <button key={`${slot.dateLabel}-${slot.time}`} className={`slot-pill ${index === 0 ? 'hot' : ''} ${active ? 'selected' : ''}`} aria-pressed={active} onClick={() => onSlotSelect(slot)}>{slot.dateLabel}<br/><b>{slot.time}</b>{active && <i>✓</i>}</button> })}</div><p className="slot-feedback" aria-live="polite">已选择 {selectedSlot.dateLabel} {selectedSlot.time}，预约表单将自动带入</p><h2 className="sub-title">选择服务</h2><div className="service-list">{services.map((service) => <button key={service.id} className={`service ${service.id === selected.id ? 'selected' : ''}`} onClick={() => onSelect(service)}><span><b>{service.name}</b><small>{service.desc}</small></span><span className="service-price">¥{service.price}<small>/次</small></span></button>)}</div><h2 className="sub-title">真实评价</h2><div className="review-card"><span className="stars">★★★★★</span><p>肩颈放松很到位，力度沟通也很细致。技师提前到达，用品都是当面拆封的。</p><small>匿名用户 · 3天前</small></div><div className="sticky-cta"><button className="primary" onClick={onBook}>立即预约 · {selectedSlot.dateLabel} {selectedSlot.time} · ¥{selected.price}</button></div></div></section>
}
