ALTER TABLE public."Technician"
  ADD COLUMN IF NOT EXISTS "experienceYears" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "arrivalTotal" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "onTimeArrivals" INTEGER NOT NULL DEFAULT 0;

UPDATE public."Technician" SET "experienceYears" = CASE "id" WHEN 1 THEN 8 WHEN 2 THEN 6 WHEN 3 THEN 5 ELSE 1 END;
