ALTER TABLE public."Technician"
  ADD COLUMN IF NOT EXISTS "workStart" TEXT NOT NULL DEFAULT '10:00',
  ADD COLUMN IF NOT EXISTS "workEnd" TEXT NOT NULL DEFAULT '22:00',
  ADD COLUMN IF NOT EXISTS "workDays" TEXT NOT NULL DEFAULT '[0,1,2,3,4,5,6]';
